url: https://trestenpool.github.io
baseurl: /Portfolio-site/

# Site settings
title: Tresten Pool
email: trestenpool@gmail.com
description: "Backend Software engineer"

# Resume set
resume: "Resume_08_23.pdf"

# certifications
certifications:
  - name: AWS Cerfified Cloud Practicioner
    url: https://www.credly.com/badges/70b777ce-3bd5-42a3-94e4-379d01667958
    img: aws-cloud-practicioner.jpeg
    description: AWS Foundational certification
    received: August 2023
  - name: Microsoft Certified Azure Fundamentals
    url: https://www.credly.com/badges/0be18762-a549-467b-9f9c-6a77cccbc69e
    img: azure-fundamentals.png
    description: Azure Fundamentals certification
    received: August 2022

# udemy certifications
udemy-certifications:
  - name: Python Django Dev to Deployment
    url: https://www.udemy.com/certificate/UC-fd79a2f4-e21a-4c2a-8bc0-47545c08a5c6/
    img: django-course.png
    description: Python Django course
    received: May 2023
  - name: Web Developer Bootcamp 2022
    url: https://www.udemy.com/certificate/UC-dd0520a4-ecd3-4530-9187-107bc7820818/
    img: web-developer-bootcamp.jpeg
    description: Web Developer bootcamp course
    received: January 2023
  - name: C Programming Master the C Language
    url: https://www.udemy.com/certificate/UC-7aa643ad-5675-429f-bccd-d4d41e2cf33a/
    img: c-language.png
    description: C language tutorial
    received: June 2022
  - name: Spring Boot 3, Spring 6 & Hibernate for Beginners
    url: https://www.udemy.com/certificate/UC-68abe4b0-8176-4607-8d56-06056bb4d770/
    img: spring-course.png
    description: Spring Boot beginner course
    received: October 2023
    

# Build settings
markdown: kramdown
permalink: pretty